### ISSUE TITLE
动态加载资源

### ISSUE THREAD

**Issue by xulong20130712** [Jarlene/ClassPatch#4]
在oncreateVIew的时候：
PatchResource patchResource = ResourceManager.getInstance().getPatchResource(mContext, apkPath);
    int resId = patchResource.getResApkLayoutId("activity_main");
    if (resId <= 0) {
        setContentView(R.layout.activity_main);
    } else {
        setContentView(resId);
    }
这个不能更新吧，因为你虽然拿的是patch中的resource id但是你当前的Resource对象还是主apk中的，主apk中的resource ID不一定能跟patch中的对应上吧。

**Comment by Jarlene** [comment]
拿到了patch的resId，但是有可能主apk中也有相同的resid，现在改成直接从patch获取view的方式：
String apkPath = HookManager.getInstance().getPatchDir(mContext).getAbsolutePath() + File.separator + "DexTest.apk";
        PatchResource patchResource = ResourceManager.getInstance().getPatchResource(mContext, apkPath);
        View resId = patchResource.getResApkLayoutView(this, "activity_main");
        if (resId == null) {
            setContentView(R.layout.activity_main);
        } else {
            setContentView(resId);
        }
